[[Qt5QuickControls2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfb490547b94b295b70a8e0cdf7f7663b1780825"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "115de326f0c9898b3d634ebeae5410bdc42f50fc8088e31d2d6162090d66dab1"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f5e08dd0462d6ce3164a473db7278068e3c0907"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "f19fc4c54ae74cab32378bc07fbc66c847137a15d3cb05faecb28d28b559a31a"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff01072a4303a5d4187294c49224e617928a6f83"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "875c0f8e10ca1fe846c32fc74d9949f71395df396d1e9558b4456cc6815178b8"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "abf85d9b4c2f95f398e33ea1647aaec5d716eb8f"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "7d880938f67e98985b89e29f847f57f5f9740e4b654f4316d011488e2974bdfa"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b60bddda2a56c1ee1a1522a5e1e0bcd2d53519fa"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "ed2bab08bfaf68a75965405a299ceaac907c70be290fd51b28df2020d8be0e60"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.i686-linux-gnu-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bad53e7aa624420b080234d1af09b2c8b0edde71"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "9964a5248f46d7770fa97f2c661f8bd843cc6562214c1da529069d69181436c8"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.i686-linux-gnu-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f3d3a672eb7cbe4dd69cc432aa3716c67b674f2"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "06c135f379fe088c7ea34f2e3c27be6be7f8dee68d00605b9a9d073b1093d932"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1cff9d74374ac1730928b895d09a2b80e04bc59"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "281ce2d4579704c3b9cbce5896dc10d6ea47477989948f18194c55c163a33904"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9748694bef404d5abdf7715e17e89a87aca7fb11"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "8961e7a19f124654187ee521a5f0b79049afb41a3e535e55c86e5b84956d7bb2"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42150ba19cb2d87a81644c0cba103818b4555294"
libc = "glibc"
os = "linux"

    [[Qt5QuickControls2.download]]
    sha256 = "b73b9f26179e74274caa1545abf4d68d71a8ddb78f468dd1cbb8b86c63810bb1"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "x86_64"
git-tree-sha1 = "55229ca03409775640908832c5f7ee19752b5606"
os = "freebsd"

    [[Qt5QuickControls2.download]]
    sha256 = "5445df9e9a0241be54011d2b365f91842cc09d2368c63d3b2924d5aa2943d06f"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.x86_64-unknown-freebsd.tar.gz"
[[Qt5QuickControls2]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94a65f65194c9d1940bfa6fc7db07d67ec5064f8"
os = "windows"

    [[Qt5QuickControls2.download]]
    sha256 = "e3ba3de3fdabce148c64957ba43ee77384a4cb9cd202bcbac1efe8337d78eec6"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.i686-w64-mingw32-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf0835de020db4f64d5766f6ce02807b74c129bb"
os = "windows"

    [[Qt5QuickControls2.download]]
    sha256 = "3de305570b0f2d6a343262904394d94648229194cc341366f73dc15969ee1fc8"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.i686-w64-mingw32-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37b9367769a098b1ced75dd44d21eb616e202b14"
os = "windows"

    [[Qt5QuickControls2.download]]
    sha256 = "c0b6205fa228a9e1d9d292837b7c41ada97133b9795d2fe7d91d9b315d1fea04"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Qt5QuickControls2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c49d4c852aa5e0a0107b39a5258c717ec86dbc3"
os = "windows"

    [[Qt5QuickControls2.download]]
    sha256 = "74f6a0f6368b9a159fd15614676c23b19e8f45df3ac5bd79e25488511325626e"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[Qt5QuickControls2]]
arch = "aarch64"
git-tree-sha1 = "001421399c4e1d704deae6ca8f3d4bf4842a98ad"
os = "macos"

    [[Qt5QuickControls2.download]]
    sha256 = "dafa6f1f0643a8373b60faf22463f16ad549dde53754170d3e2c2199a50c598d"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.aarch64-apple-darwin.tar.gz"
[[Qt5QuickControls2]]
arch = "x86_64"
git-tree-sha1 = "1354fcdce852001d4c0ba29defdfd26239f730db"
os = "macos"

    [[Qt5QuickControls2.download]]
    sha256 = "10c7daa60304dc64c2af65988367ae41bb586a00ce7a376d6edffc834b6c00d0"
    url = "https://github.com/JuliaBinaryWrappers/Qt5QuickControls2_jll.jl/releases/download/Qt5QuickControls2-v5.15.3+0/Qt5QuickControls2.v5.15.3.x86_64-apple-darwin.tar.gz"
